import EconomicsHumanCapitalCanonicalLaneLean.HumanCapitalProductionFunction
import EconomicsHumanCapitalCanonicalLaneLean.MincerEquation
import EconomicsHumanCapitalCanonicalLaneLean.BenPorathLifeCycle
import EconomicsHumanCapitalCanonicalLaneLean.NelsonPhelpsTechnologicalAdoption
import EconomicsHumanCapitalCanonicalLaneLean.HumanCapitalBridgeLemmas
import EconomicsHumanCapitalCanonicalLaneLean.HumanCapitalGateLemmas
import EconomicsHumanCapitalCanonicalLaneLean.ConstrainedHumanCapitalClosure

namespace HautevilleHouse
namespace EconomicsHumanCapitalCanonicalLaneLean

theorem all_theorems_imported : True := by
  trivial

end EconomicsHumanCapitalCanonicalLaneLean
end HautevilleHouse